### ISSUE TITLE
Noelle Issues

### ISSUE THREAD

**Issue by lakinsm** [lakinsm/wgs-meg#3]
1. Install MetAmos on abdo2
2. modify kSNP command to include ML and core SNP outputs
3. Change workflow graphic on Google Docs

**Comment by noellenoyes** [comment]
Progress update:
1. metAMOS is installed and mostly functioning, but we need to move jellyfish on abdo2 so that it's not in /usr/bin, and then reinstall metAMOS
2. DONE
3. I need Steven and Chris to verify that the red, blue and orange lines are correct in terms of which output goes into which step of the pipeline. Other than that, the graphic is ready to go.
